const $=s=>document.querySelector(s);let supabaseClient,session,mode='paper',positions=[],signals=[];
async function boot(){const cfg=await fetch('/config').then(r=>r.json());supabaseClient=window.supabase.createClient(cfg.supabase_url,cfg.supabase_anon_key);const r=await supabaseClient.auth.getSession();session=r.data.session;if(!session){location.href='/login';return}$('#userName').textContent=session.user.email||session.user.user_metadata?.name||'User';await loadAll();subscribe();}
async function api(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,...(options.headers||{})}});if(res.status===401){location.href='/login'}if(!res.ok)throw new Error(await res.text());return res.status===204?null:res.json()}
async function loadAll(){try{const d=await api('/dashboard/summary?mode='+mode);renderSummary(d)}catch(e){}try{const a=await api('/coins/allocated');renderAllocations(a)}catch(e){}try{positions=await api('/positions/active?mode='+mode);renderPositions(positions)}catch(e){}try{signals=await api('/forecast/signals/latest');renderSignals(signals)}catch(e){}try{const h=await api('/positions/history?limit=5&mode='+mode);renderHistory(h)}catch(e){}}
function money(v){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0))}function num(v){return Number(v||0).toLocaleString('id-ID',{maximumFractionDigits:8})}function time(v){return v?new Date(v).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'}):'-'}
function renderSummary(d){$('#balance').textContent=money(d.balance);$('#dailyPnl').textContent=money(d.daily_pnl);$('#dailyPnl').className=Number(d.daily_pnl)>=0?'profit':'loss';$('#dailyPnlPct').textContent=`${Number(d.daily_pnl_percent||0).toFixed(2)}%`;$(`#openCount`).textContent=d.open_positions??positions.length;$('#balanceMode').textContent=mode==='paper'?'Paper balance':'Indodax balance';$('#positionMode').textContent=mode==='paper'?'Paper Trading':'Live Trading'}
function renderAllocations(a){const list=Array.isArray(a)?a:(a.coins||[]);$('#allocationList').innerHTML=list.length?list.map(x=>`<div class="coin"><strong>${x.symbol}</strong><small>${Number(x.allocation_percent||0).toFixed(2)}% alokasi</small></div>`).join(''):'<div class="empty">Belum ada coin.</div>'}
function renderPositions(p){const list=Array.isArray(p)?p:(p.positions||[]);$('#openCount').textContent=list.length;$('#positionsBody').innerHTML=list.length?list.map(x=>`<tr><td><strong>${x.symbol}</strong></td><td>${num(x.entry_price)}</td><td>${num(x.tp_price)}</td><td>${num(x.sl_price)}</td><td>${x.status||'open'}</td><td>${time(x.opened_at)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Tidak ada posisi aktif.</td></tr>'}
function renderSignals(s){const list=Array.isArray(s)?s:(s.signals||[]);$('#forecastList').innerHTML=list.length?list.slice(0,5).map(x=>`<div class="forecast"><div class="forecast-top"><strong>${x.symbol}</strong><span>${(Number(x.confidence||0)*100).toFixed(0)}%</span></div><div class="forecast-grid"><div><span>TP</span><strong class="profit">${num(x.suggested_tp)}</strong></div><div><span>SL</span><strong class="loss">${num(x.suggested_sl)}</strong></div><div><span>Confidence</span><strong>${Number(x.confidence||0).toFixed(2)}</strong></div></div></div>`).join(''):'<div class="empty">Belum ada sinyal.</div>'}
function renderHistory(h){const list=Array.isArray(h)?h:(h.positions||[]);$('#historyList').innerHTML=list.slice(0,5).map(x=>`<div class="history"><span><strong>${x.symbol}</strong><br><small>${time(x.closed_at)}</small></span><strong class="${Number(x.pnl)>=0?'profit':'loss'}">${Number(x.pnl)>=0?'+':''}${money(x.pnl)}</strong></div>`).join('')||'<div class="empty">Belum ada transaksi.</div>'}
function subscribe(){supabaseClient.channel('dashboard-realtime').on('postgres_changes',{event:'*',schema:'public',table:mode==='paper'?'paper_positions':'positions'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'forecast_signals'},()=>loadAll()).subscribe()}
async function setMode(next){if(next===mode)return;if(next==='live'&&!confirm('Pindah ke LIVE TRADING? Order dapat menggunakan saldo nyata.'))return;try{await api('/trading/mode',{method:'POST',body:JSON.stringify({mode:next})});mode=next;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));await loadAll();}catch(e){alert('Mode gagal diubah.');}}
$('#botToggle').onclick=async()=>{try{const r=await api('/bot/toggle',{method:'POST'});const active=!!r.active;$('#botStatus').textContent=active?'Aktif':'Berhenti';$('#botStatus').className='status '+(active?'active':'stopped');$('#botToggle').textContent=active?'Hentikan Bot':'Mulai Bot'}catch(e){alert('Status bot gagal diubah.')}};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#allocationBtn').onclick=async()=>{const d=$('#allocationDialog');d.showModal();try{const data=await api('/coins/available');const coins=Array.isArray(data)?data:(data.coins||[]);const current=await api('/coins/allocated');const cur=Array.isArray(current)?current:(current.coins||[]);const map=new Map(cur.map(x=>[x.symbol,x.allocation_percent]));$('#availableCoins').innerHTML=coins.map(x=>{const symbol=x.symbol||x.ticker_id;const checked=map.has(symbol)?'checked':'';return `<label class="coin-option"><input type="checkbox" value="${symbol}" ${checked}><span>${symbol}<small>${x.description||x.base_coin||''}</small></span><input type="number" min="0" max="100" step="0.1" data-pct="${symbol}" value="${map.get(symbol)||0}"></label>`}).join('')}catch(e){$('#availableCoins').innerHTML='<div class="empty">Gagal mengambil daftar coin.</div>'}};
$('#saveAllocation').onclick=async()=>{const rows=[...document.querySelectorAll('.coin-option')].filter(r=>r.querySelector('input[type=checkbox]').checked).map(r=>({symbol:r.querySelector('input[type=checkbox]').value,allocation_percent:Number(r.querySelector('input[data-pct]').value)}));if(rows.length>6)return alert('Maksimal 6 coin.');const total=rows.reduce((a,x)=>a+x.allocation_percent,0);if(Math.abs(total-100)>0.01)return alert('Total alokasi harus 100%.');try{await api('/coins/allocate',{method:'POST',body:JSON.stringify({coins:rows})});$('#allocationDialog').close();loadAll()}catch(e){alert('Alokasi gagal disimpan.')}};
window.addEventListener('beforeunload',()=>supabaseClient?.removeAllChannels());boot();
