const sb=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_PUBLISHABLE_KEY);
let session=null,mode="paper",channel=null;
const $=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const num=v=>Number(v||0).toLocaleString("id-ID",{maximumFractionDigits:8});
const time=v=>v?new Date(v).toLocaleString("id-ID",{dateStyle:"short",timeStyle:"short"}):"-";
async function api(path,opts={}){if(!APP_CONFIG.API_BASE_URL||APP_CONFIG.API_BASE_URL.includes("YOUR-"))throw Error("API_BASE_URL belum dikonfigurasi");let r;try{r=await fetch(APP_CONFIG.API_BASE_URL.replace(/\/$/,"")+path,{...opts,headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,...(opts.headers||{})}})}catch(e){throw Error(`API tidak dapat dihubungi: ${e.message}`)}let body;try{body=await r.json()}catch{body=null}if(r.status===401){await sb.auth.signOut();location.href="./login.html";throw Error("Session expired")}if(!r.ok)throw Error(body?.detail||body?.message||`API error ${r.status}`);return body}
async function load(){const d=await api(`/dashboard/summary?mode=${mode}`);$("#balance").textContent=money(d.balance);$("#dailyPnl").textContent=money(d.today_pnl);$("#dailyPnl").className=Number(d.today_pnl)>=0?"profit":"loss";$("#dailyPnlPct").textContent=`${Number(d.today_pnl_percent||0).toFixed(2)}%`;$("#openCount").textContent=d.open_positions.length;$("#balanceMode").textContent=mode==="paper"?"Paper balance":"Indodax balance";$("#positionMode").textContent=mode==="paper"?"Paper Trading":"Live Trading";$("#botStatus").textContent=d.bot_enabled?"Aktif":"Berhenti";$("#botStatus").className="status "+(d.bot_enabled?"active":"stopped");$("#botToggle").textContent=d.bot_enabled?"Hentikan Bot":"Mulai Bot";renderAllocations(await api("/coins/allocated"));renderPositions(d.open_positions);renderSignals(d.signals);renderHistory(d.transactions)}
function renderAllocations(a){$("#allocationList").innerHTML=a?.length?a.map(x=>`<div class="coin"><strong>${x.symbol}</strong><small>${Number(x.allocation_percent).toFixed(2)}% alokasi</small></div>`).join(""):`<div class="empty">Belum ada coin.</div>`}
function renderPositions(a){$("#positionsBody").innerHTML=a?.length?a.map(x=>`<tr><td><strong>${x.symbol}</strong></td><td>${num(x.entry_price)}</td><td>${num(x.tp_price)}</td><td>${num(x.sl_price)}</td><td>${num(x.quantity)}</td><td>${x.status}</td></tr>`).join(""):`<tr><td colspan="6" class="empty">Tidak ada posisi aktif.</td></tr>`}
function renderSignals(a){$("#forecastList").innerHTML=a?.length?a.map(x=>`<div class="forecast"><div class="forecast-top"><strong>${x.symbol}</strong><span>${(Number(x.confidence)*100).toFixed(0)}%</span></div><div class="forecast-grid"><div><span>TP</span><strong class="profit">${num(x.suggested_tp)}</strong></div><div><span>SL</span><strong class="loss">${num(x.suggested_sl)}</strong></div><div><span>Aksi</span><strong>${x.action}</strong></div></div></div>`).join(""):`<div class="empty">Belum ada sinyal.</div>`}
function renderHistory(a){$("#historyList").innerHTML=a?.length?a.slice(0,5).map(x=>`<div class="history"><span><strong>${x.symbol}</strong><br><small>${time(x.closed_at)}</small></span><strong class="${Number(x.pnl)>=0?"profit":"loss"}">${Number(x.pnl)>=0?"+":""}${money(x.pnl)}</strong></div>`).join(""):`<div class="empty">Belum ada transaksi.</div>`}
function subscribe(){channel?.unsubscribe();channel=sb.channel(`dashboard-${mode}`).on("postgres_changes",{event:"*",schema:"public",table:"positions",filter:`user_id=eq.${session.user.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"forecast_signals",filter:`user_id=eq.${session.user.id}`},load).subscribe()}
async function setMode(next){if(next===mode)return;if(next==="live"&&!confirm("Pindah ke LIVE TRADING?"))return;try{await api("/dashboard/mode",{method:"POST",body:JSON.stringify({mode:next})});mode=next;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));await load();subscribe()}catch(e){alert(e.message)}}
$("#botToggle").onclick=async()=>{try{await api("/dashboard/bot/toggle",{method:"POST"});await load()}catch(e){alert(e.message)}};
document.querySelectorAll(".mode").forEach(x=>x.onclick=()=>setMode(x.dataset.mode));
$("#allocationBtn").onclick=async()=>{const dialog=$("#allocationDialog");dialog.showModal();try{const [coins,current]=await Promise.all([api("/coins/available"),api("/coins/allocated")]);const map=new Map(current.map(x=>[x.symbol,Number(x.allocation_percent)]));$("#availableCoins").innerHTML=coins.map(x=>{const s=x.symbol;return `<label class="coin-option"><input type="checkbox" value="${s}" ${map.has(s)?"checked":""}><span>${s}<small>${x.description||x.base_coin||""}</small></span><input type="number" min="0" max="100" step="0.1" data-pct="${s}" value="${map.get(s)||0}"></label>`}).join("")}catch(e){$("#availableCoins").innerHTML=`<div class="empty">${e.message}</div>`}};
$("#saveAllocation").onclick=async()=>{const rows=[...document.querySelectorAll(".coin-option")].filter(r=>r.querySelector('input[type="checkbox"]').checked).map(r=>({symbol:r.querySelector('input[type="checkbox"]').value,allocation_percent:Number(r.querySelector("[data-pct]").value)}));const total=rows.reduce((a,x)=>a+x.allocation_percent,0);if(rows.length>6)return alert("Maksimal 6 coin.");if(Math.abs(total-100)>0.01)return alert("Total alokasi harus 100%.");try{await api("/coins/allocate",{method:"POST",body:JSON.stringify({coins:rows})});$("#allocationDialog").close();await load()}catch(e){alert(e.message)}};
async function boot(){const {data}=await sb.auth.getSession();session=data.session;if(!session){location.href="./login.html";return}$("#userName").textContent=session.user.email||"User";try{await api("/auth/me");await load();subscribe()}catch(e){alert(e.message)}}
window.addEventListener("beforeunload",()=>channel?.unsubscribe());boot();
