import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Alert, AppBar, Box, Button, Card, CardContent, Chip, Divider, FormControl, Grid, IconButton, InputLabel, LinearProgress, Menu, MenuItem, Paper, Select, Stack, ToggleButton, ToggleButtonGroup, Toolbar, Typography } from '@mui/material';
import { AccountCircle, LockOutlined, Logout, Refresh, ShowChart, TrendingDown, TrendingUp } from '@mui/icons-material';
import axios from 'axios';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';

const PAIRS = [['btc_idr', 'BTC/IDR'], ['eth_idr', 'ETH/IDR'], ['usdt_idr', 'USDT/IDR'], ['xrp_idr', 'XRP/IDR'], ['doge_idr', 'DOGE/IDR'], ['sol_idr', 'SOL/IDR']];
const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0);
const num = (value, digits = 2) => Number.isFinite(Number(value)) ? Number(value).toLocaleString('id-ID', { maximumFractionDigits: digits }) : '—';

function PriceChart({ points }) {
  const values = (points || []).map((p) => Number(p.price)).filter((p) => Number.isFinite(p) && p > 0);
  if (values.length < 2) return <Box sx={{ height: 220, display: 'grid', placeItems: 'center', color: 'text.secondary' }}>Waiting for recent INDODAX trades…</Box>;
  const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1;
  const coords = values.map((v, i) => `${(i / (values.length - 1)) * 100},${95 - ((v - min) / range) * 85}`).join(' ');
  return <Box sx={{ height: 220, px: 1 }}><svg viewBox="0 0 100 100" width="100%" height="190" preserveAspectRatio="none"><polyline points={coords} fill="none" stroke="currentColor" strokeWidth="1.2" vectorEffect="non-scaling-stroke" /></svg><Stack direction="row" justifyContent="space-between" sx={{ color: 'text.secondary', fontSize: 12 }}><span>{money(min)}</span><span>{money(max)}</span></Stack></Box>;
}
function HealthItem({ label, ok, value }) { return <Stack direction="row" justifyContent="space-between"><Stack direction="row" spacing={1} alignItems="center"><Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: ok ? 'success.main' : 'error.main' }} /><Typography variant="body2">{label}</Typography></Stack><Typography variant="caption" fontWeight={700} color={ok ? 'success.main' : 'error.main'}>{value}</Typography></Stack>; }

export default function Dashboard() {
  const navigate = useNavigate();
  const { logout, user } = useAuth();
  const [menu, setMenu] = useState(null); const [loading, setLoading] = useState(false); const [actionLoading, setActionLoading] = useState(false);
  const [pair, setPair] = useState(localStorage.getItem('paperTradingPair') || 'btc_idr'); const [mode, setMode] = useState('paper');
  const [status, setStatus] = useState(null); const [positions, setPositions] = useState([]); const [performance, setPerformance] = useState(null); const [decision, setDecision] = useState(null); const [agents, setAgents] = useState([]); const [market, setMarket] = useState(null); const [insights, setInsights] = useState([]);
  const [history, setHistory] = useState(() => { try { return JSON.parse(localStorage.getItem('aiDecisionObservations') || '[]'); } catch { return []; } });
  const [targets, setTargets] = useState(() => { try { return { daily: 0, weekly: 0, monthly: 0, ...JSON.parse(localStorage.getItem('paperTradingTargets') || '{}') }; } catch { return { daily: 0, weekly: 0, monthly: 0 }; } });
  const botOn = Boolean(status?.enabled); const pairLabel = PAIRS.find(([v]) => v === pair)?.[1] || pair.toUpperCase();

  const fetchData = useCallback(async () => {
    setLoading(true);
    const requests = [
      ['status', axios.get('/api/dashboard/status')], ['positions', axios.get('/api/dashboard/positions')], ['performance', axios.get('/api/dashboard/performance')],
      ['decision', axios.get('/api/dashboard/recent-decision')], ['agents', axios.get('/api/dashboard/agents')], ['market', axios.get('/api/market/overview', { params: { pair } })], ['insights', axios.get('/api/market/insights')],
    ];
    const results = await Promise.allSettled(requests.map(([, request]) => request)); let failures = 0;
    results.forEach((result, index) => {
      const key = requests[index][0]; if (result.status !== 'fulfilled') { failures += 1; return; } const payload = result.value.data;
      if (key === 'status') setStatus(payload); if (key === 'positions') setPositions(payload.positions || []); if (key === 'performance') setPerformance(payload.performance || null); if (key === 'decision') setDecision(payload.decision || null); if (key === 'agents') setAgents(payload.agents || []); if (key === 'market') setMarket(payload); if (key === 'insights') setInsights(payload.items || []);
    });
    const dResult = results[3]; const mResult = results[5];
    if (dResult.status === 'fulfilled' && dResult.value.data?.decision) {
      const d = dResult.value.data.decision; const m = mResult.status === 'fulfilled' ? mResult.value.data : null;
      const item = { timestamp: d.timestamp || d.created_at || new Date().toISOString(), action: String(d.action || d.final_action || 'HOLD').toUpperCase(), confidence: Number(d.confidence ?? d.final_confidence ?? 0) * 100, move: m?.recent_move == null ? null : Number(m.recent_move), pair: pairLabel };
      setHistory((current) => { if (current[0]?.timestamp === item.timestamp) return current; const next = [item, ...current].slice(0, 20); localStorage.setItem('aiDecisionObservations', JSON.stringify(next)); return next; });
    }
    if (failures > 0 && failures < requests.length) toast.error(`${failures} dashboard service${failures > 1 ? 's' : ''} unavailable; healthy panels remain visible.`);
    if (failures === requests.length) toast.error('Dashboard API is unavailable.');
    setLoading(false);
  }, [pair, pairLabel]);
  useEffect(() => { fetchData(); const interval = setInterval(fetchData, 60000); return () => clearInterval(interval); }, [fetchData]);

  const toggleBot = async () => { if (mode !== 'paper' || actionLoading) return; setActionLoading(true); try { if (botOn) await axios.post('/api/dashboard/paper/stop'); else await axios.post('/api/dashboard/paper/start', null, { params: { pair } }); toast.success(botOn ? 'Paper trading stopped.' : 'Paper trading enabled.'); await fetchData(); } catch (error) { toast.error(error.response?.data?.detail || error.response?.data?.error || 'Paper trading control failed.'); await fetchData(); } finally { setActionLoading(false); } };
  const analyze = async () => { if (!botOn) return toast('BOT is OFF. Start paper trading first.'); try { toast.loading('Running AI analysis…', { id: 'analysis' }); await axios.post('/api/dashboard/analyze', null, { params: { symbol: pair } }); toast.success('AI analysis completed.', { id: 'analysis' }); await fetchData(); } catch (error) { toast.error(error.response?.data?.detail || 'AI analysis failed.', { id: 'analysis' }); } };
  const saveTarget = (key, value) => { const next = { ...targets, [key]: Math.max(0, Number(value) || 0) }; setTargets(next); localStorage.setItem('paperTradingTargets', JSON.stringify(next)); };

  const health = status?.system_health || {}; const aiEngine = status?.ai_engine || {}; const counts = status?.decision_counts || { BUY: 0, SELL: 0, HOLD: 0 }; const dailyPnl = Number(status?.daily_pnl || 0); const move = Number(market?.recent_move); const action = String(decision?.action || decision?.final_action || 'HOLD').toUpperCase(); const confidence = Number(decision?.confidence ?? decision?.final_confidence ?? 0) * 100; const scores = decision?.market_scores || {};
  const votes = Object.values(decision?.votes || decision?.agent_votes || {}).map((v) => String(v).toUpperCase()); const buyVotes = votes.filter((v) => v === 'BUY').length; const sellVotes = votes.filter((v) => v === 'SELL').length; const holdVotes = votes.filter((v) => v === 'HOLD').length; const consensus = Math.max(buyVotes, sellVotes, holdVotes) / Math.max(1, votes.length) * 100; const scanner = useMemo(() => insights.slice(0, 8), [insights]);

  return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}>
    <AppBar position="static"><Toolbar><ShowChart sx={{ mr: 1.5 }} /><Typography variant="h6" sx={{ flexGrow: 1 }}>AI Trading Dashboard</Typography><Chip label={botOn ? 'BOT ON' : 'BOT OFF'} color={botOn ? 'success' : 'default'} size="small" sx={{ mr: 1.5, fontWeight: 700 }} /><Button color="inherit" startIcon={<Refresh />} disabled={!botOn || mode !== 'paper'} onClick={analyze}>Analyze</Button><IconButton color="inherit" onClick={(e) => setMenu(e.currentTarget)}><AccountCircle /></IconButton><Menu anchorEl={menu} open={Boolean(menu)} onClose={() => setMenu(null)}><MenuItem disabled>{user?.username || 'Admin'}</MenuItem><Divider /><MenuItem onClick={() => { setMenu(null); navigate('/reports'); }}>Reports</MenuItem><MenuItem onClick={async () => { setMenu(null); await logout(); navigate('/login'); }}><Logout sx={{ mr: 1 }} fontSize="small" />Logout</MenuItem></Menu></Toolbar></AppBar>
    {loading && <LinearProgress />}
    <Box sx={{ p: { xs: 1.5, md: 3 } }}>
      <Paper sx={{ p: 2.5, mb: 3 }}><Grid container spacing={2} alignItems="center"><Grid item xs={12} md={5}><Typography variant="overline" color="text.secondary">Trading Environment</Typography><Typography variant="h5">Paper Trading</Typography><Typography variant="body2" color="text.secondary">Paper execution is the active validation environment. Real trading remains locked.</Typography></Grid><Grid item xs={12} md={3}><FormControl fullWidth size="small"><InputLabel>Trading Pair</InputLabel><Select value={pair} label="Trading Pair" onChange={(e) => { setPair(e.target.value); localStorage.setItem('paperTradingPair', e.target.value); }}>{PAIRS.map(([v, label]) => <MenuItem key={v} value={v}>{label}</MenuItem>)}</Select></FormControl></Grid><Grid item xs={12} md={4} sx={{ display: 'flex', justifyContent: { md: 'flex-end' } }}><ToggleButtonGroup value={mode} exclusive onChange={(_, value) => value && setMode(value)}><ToggleButton value="paper">PAPER</ToggleButton><ToggleButton value="real" disabled><LockOutlined sx={{ mr: .5, fontSize: 17 }} />REAL</ToggleButton></ToggleButtonGroup></Grid></Grid><Alert severity={botOn ? 'success' : 'info'} sx={{ mt: 2 }}>{botOn ? `Paper bot is RUNNING on ${pairLabel}.` : 'Safety mode: BOT OFF. Selecting, refreshing, or viewing the dashboard never starts an AI cycle.'}</Alert></Paper>

      <Grid container spacing={3} sx={{ mb: 3 }}><Grid item xs={12} md={8}><Paper sx={{ p: 2.5, height: '100%' }}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h6">Market Pulse</Typography><Typography variant="caption" color="text.secondary">{pairLabel} · INDODAX public API · recent trades</Typography></Box><Typography variant="h6">{market?.last ? money(market.last) : '—'}</Typography></Stack><PriceChart points={market?.points} /><Grid container spacing={1}><Grid item xs={6} md={3}><Typography variant="caption" color="text.secondary">24h High</Typography><Typography>{market?.high ? money(market.high) : '—'}</Typography></Grid><Grid item xs={6} md={3}><Typography variant="caption" color="text.secondary">24h Low</Typography><Typography>{market?.low ? money(market.low) : '—'}</Typography></Grid><Grid item xs={6} md={3}><Typography variant="caption" color="text.secondary">Recent Move</Typography><Typography color={move > 0 ? 'success.main' : move < 0 ? 'error.main' : 'text.primary'}>{Number.isFinite(move) ? `${move > 0 ? '+' : ''}${move.toFixed(2)}%` : '—'}</Typography></Grid><Grid item xs={6} md={3}><Typography variant="caption" color="text.secondary">24h Volume</Typography><Typography>{market?.volume ? money(market.volume) : '—'}</Typography></Grid></Grid></Paper></Grid><Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Market Scanner</Typography><Typography variant="caption" color="text.secondary">Top IDR-volume public tickers. No orders are placed.</Typography><Stack spacing={1} sx={{ mt: 1.5 }}>{scanner.map((item) => <Card key={item.pair} variant="outlined"><CardContent sx={{ py: 1, '&:last-child': { pb: 1 } }}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="subtitle2">{item.pair}</Typography><Typography variant="caption" color="text.secondary">{money(item.last)} · Vol {money(item.volume_idr)}</Typography></Box><Chip icon={item.range_position >= 50 ? <TrendingUp /> : <TrendingDown />} label={item.signal} size="small" color={item.range_position >= 80 ? 'success' : item.range_position <= 20 ? 'error' : 'default'} /></Stack></CardContent></Card>)}{!scanner.length && <Typography color="text.secondary">Market scanner unavailable.</Typography>}</Stack></Paper></Grid></Grid>

      <Grid container spacing={3} sx={{ mb: 3 }}>{[['Portfolio Value', money(status?.portfolio_value || status?.balance), `Balance: ${money(status?.balance)}`], ['Daily PnL', money(dailyPnl), `${status?.daily_trades || 0} trades today`], ['Active Positions', String(status?.active_positions || positions.length || 0), 'Max: 5'], ['Total Trades', String(status?.total_trades || 0), `Win rate: ${num(Number(performance?.win_rate || 0) * 100, 1)}%`]].map(([title, value, sub]) => <Grid item xs={12} sm={6} md={3} key={title}><Paper sx={{ p: 2.2 }}><Typography variant="caption" color="text.secondary">{title}</Typography><Typography variant="h6">{value}</Typography><Typography variant="caption" color="text.secondary">{sub}</Typography></Paper></Grid>)}</Grid>

      <Grid container spacing={3} sx={{ mb: 3 }}><Grid item xs={12} md={5}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Paper Trading Control</Typography><Typography variant="caption" color="text.secondary">Manual gate. Durable Object Alarm runs only after BOT ON.</Typography><Button fullWidth sx={{ mt: 2 }} variant="contained" color={botOn ? 'error' : 'success'} disabled={actionLoading} onClick={toggleBot}>{actionLoading ? 'PROCESSING…' : botOn ? 'STOP PAPER BOT' : 'START PAPER BOT'}</Button><Typography variant="caption" display="block" color="text.secondary" sx={{ mt: 1 }}>AI source: {aiEngine.source || 'FastAPI Cloud + local fallback'}. External configured: {aiEngine.configured ? 'yes' : 'no — local fallback active'}.</Typography></Paper></Grid><Grid item xs={12} md={7}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Agent Score Radar</Typography><Typography variant="caption" color="text.secondary">Latest multi-agent market scores. This panel never triggers analysis.</Typography><Grid container spacing={1.5} sx={{ mt: 1 }}>{['sentiment', 'technical', 'forecast', 'range_position'].map((key) => { const raw = Number(scores[key] || 0); const value = key === 'range_position' ? raw * 100 : raw * 100; return <Grid item xs={6} key={key}><Typography variant="caption" sx={{ textTransform: 'capitalize' }}>{key.replace('_', ' ')}</Typography><LinearProgress variant="determinate" value={Math.max(0, Math.min(100, value))} sx={{ height: 8, borderRadius: 4, mt: .5 }} /></Grid>; })}</Grid><Stack direction="row" spacing={1} sx={{ mt: 2 }}><Chip label={`AI ${action}`} color={action === 'BUY' ? 'success' : action === 'SELL' ? 'error' : 'default'} /><Chip label={`Confidence ${Number.isFinite(confidence) ? confidence.toFixed(1) : '—'}%`} /><Chip label={`Consensus ${consensus.toFixed(0)}%`} /></Stack></Paper></Grid></Grid>

      <Grid container spacing={3} sx={{ mb: 3 }}><Grid item xs={12} md={5}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">System Health</Typography><Typography variant="caption" color="text.secondary">Worker and paper-state diagnostics.</Typography><Stack spacing={1.4} sx={{ mt: 2 }}><HealthItem label="Database" ok={health.database?.connected === true} value={health.database?.connected ? 'CONNECTED' : 'DISCONNECTED'} /><HealthItem label="Market data" ok={health.market_data?.fresh === true} value={health.market_data?.fresh ? 'FRESH' : 'STALE'} /><HealthItem label="Mode" ok={health.mode === 'paper'} value={String(health.mode || 'paper').toUpperCase()} /><HealthItem label="Engine" ok={health.engine?.running === true} value={health.engine?.running ? 'RUNNING' : 'OFF'} /></Stack></Paper></Grid><Grid item xs={12} md={7}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">AI Consensus</Typography><Typography variant="caption" color="text.secondary">Votes from the latest AI result.</Typography><Stack direction="row" spacing={1} sx={{ mt: 2, mb: 2 }}><Chip label={`BUY ${buyVotes}`} color="success" /><Chip label={`HOLD ${holdVotes}`} /><Chip label={`SELL ${sellVotes}`} color="error" /></Stack><Typography variant="body2">{decision?.summary || 'Waiting for the first AI cycle.'}</Typography><Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>Agents: {agents.length || 5} · Source: {decision?.source || aiEngine.source || 'AI ensemble'}</Typography></Paper></Grid></Grid>

      <Grid container spacing={3} sx={{ mb: 3 }}><Grid item xs={12} md={7}><Paper sx={{ p: 2.5 }}><Typography variant="h6">Decision History</Typography><Stack spacing={1} sx={{ mt: 1.5 }}>{history.slice(0, 8).map((item, i) => <Card key={`${item.timestamp}-${i}`} variant="outlined"><CardContent sx={{ py: .9, '&:last-child': { pb: .9 } }}><Stack direction="row" justifyContent="space-between"><Typography variant="caption">{new Date(item.timestamp).toLocaleString('id-ID')}</Typography><Chip size="small" label={item.action} color={item.action === 'BUY' ? 'success' : item.action === 'SELL' ? 'error' : 'default'} /></Stack><Typography variant="caption" color="text.secondary">{item.pair} · move {item.move == null ? '—' : `${Number(item.move).toFixed(2)}%`} · confidence {Number(item.confidence || 0).toFixed(0)}%</Typography></CardContent></Card>)}{!history.length && <Typography color="text.secondary">No decisions recorded yet.</Typography>}</Stack></Paper></Grid><Grid item xs={12} md={5}><Paper sx={{ p: 2.5 }}><Typography variant="h6">Evaluation Targets</Typography><Typography variant="caption" color="text.secondary">Local targets; they do not change bot risk settings.</Typography><Stack spacing={1.5} sx={{ mt: 2 }}>{['daily', 'weekly', 'monthly'].map((key) => <Stack direction="row" alignItems="center" spacing={1} key={key}><Typography sx={{ width: 70, textTransform: 'capitalize' }}>{key}</Typography><input aria-label={`${key} target`} type="number" min="0" value={targets[key]} onChange={(e) => saveTarget(key, e.target.value)} style={{ width: '100%', padding: 8, borderRadius: 6, border: '1px solid #555', background: 'transparent', color: 'inherit' }} /></Stack>)}</Stack><LinearProgress variant="determinate" value={targets.daily > 0 ? Math.max(0, Math.min(100, dailyPnl / targets.daily * 100)) : 0} sx={{ mt: 2 }} /></Paper></Grid></Grid>

      <Grid container spacing={3}><Grid item xs={12}><Paper sx={{ p: 2.5 }}><Typography variant="h6">Active Positions</Typography>{positions.length ? <Stack spacing={1} sx={{ mt: 1.5 }}>{positions.map((p, i) => <Card key={`${p.symbol}-${i}`} variant="outlined"><CardContent sx={{ py: 1 }}><Stack direction="row" justifyContent="space-between"><Typography>{p.symbol}</Typography><Typography>{p.side} · Qty {num(p.quantity, 8)}</Typography><Typography>{money(p.unrealized_pnl)}</Typography></Stack></CardContent></Card>)}</Stack> : <Typography color="text.secondary" sx={{ mt: 1 }}>No active paper positions.</Typography>}</Paper></Grid></Grid>
    </Box>
  </Box>;
}
