import React, { useEffect, useMemo, useState } from 'react';
import { Box, Card, CardContent, Chip, Grid, LinearProgress, Paper, Select, MenuItem, FormControl, InputLabel, Stack, TextField, Typography } from '@mui/material';
import { TrendingDown, TrendingUp, Remove } from '@mui/icons-material';
import axios from 'axios';
import { Chart as ChartJS, RadialLinearScale, PointElement, LineElement, Filler, Tooltip, Legend, CategoryScale, LinearScale, LineController } from 'chart.js';
import { Radar, Line } from 'react-chartjs-2';

ChartJS.register(RadialLinearScale, PointElement, LineElement, Filler, Tooltip, Legend, CategoryScale, LinearScale, LineController);
const idr = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0);
const today = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const Indicator = ({ label, ok, value }) => <Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" spacing={1} alignItems="center"><Box sx={{ width: 9, height: 9, borderRadius: '50%', bgcolor: ok ? 'success.main' : 'error.main' }} /><Typography variant="body2">{label}</Typography></Stack><Typography variant="caption" color={ok ? 'success.main' : 'error.main'} fontWeight={700}>{value}</Typography></Stack>;

export default function DashboardTools({ market, decision, counts, runtimeHours = 0, cycles = 0, targets, dailyActual = 0, decisionHistory = [], positions = [] }) {
  const [health, setHealth] = useState(null); const [maxPositions, setMaxPositions] = useState(3); const [historyDate, setHistoryDate] = useState(today()); const [history, setHistory] = useState([]); const [historyLoading, setHistoryLoading] = useState(false); const [historyError, setHistoryError] = useState('');
  const loadHealth = async () => { try { const response = await axios.get('/api/dashboard/status', { params: { _ts: Date.now() }, headers: { 'Cache-Control': 'no-cache' } }); const data = response.data || {}; setHealth(data.system_health || null); const server = Number(data.max_open_positions); if (server >= 1 && server <= 3) setMaxPositions(server); } catch (error) { console.error('System health request failed', error); } };
  const loadHistory = async (date) => { setHistoryLoading(true); setHistoryError(''); try { const response = await axios.get('/api/dashboard/history', { params: { date, _ts: Date.now() }, headers: { 'Cache-Control': 'no-cache' } }); setHistory(response.data?.history || []); } catch (error) { setHistory([]); setHistoryError(error.response?.data?.detail || (error.response?.status === 404 ? 'History route is not deployed yet.' : 'History unavailable')); } finally { setHistoryLoading(false); } };
  useEffect(() => { loadHealth(); const timer = setInterval(loadHealth, 5000); return () => clearInterval(timer); }, []);
  useEffect(() => { loadHistory(historyDate); }, [historyDate]);
  const saveLimit = async (event) => { const value = Math.max(1, Math.min(3, Number(event.target.value) || 3)); const previous = maxPositions; setMaxPositions(value); try { const response = await axios.post('/api/dashboard/paper/settings', { max_open_positions: value }); const confirmed = Number(response.data?.max_open_positions); if (confirmed >= 1 && confirmed <= 3) setMaxPositions(confirmed); else setMaxPositions(value); } catch (error) { setMaxPositions(previous); console.error('Position limit update failed', error); } };
  const action = String(decision?.action || 'HOLD').toUpperCase(); const move = Number(market?.recent_move); const range = Number(market?.range_position); const condition = Number.isFinite(range) ? range >= 75 ? 'NEAR 24H HIGH' : range <= 25 ? 'NEAR 24H LOW' : 'MID 24H RANGE' : 'UNAVAILABLE'; const marketBias = Number.isFinite(move) ? move > 0.5 ? 'RISING' : move < -0.5 ? 'FALLING' : 'FLAT' : condition; const confidence = Number(decision?.confidence || 0); const confidencePct = confidence <= 1 ? confidence * 100 : confidence; const observation = marketBias === 'RISING' && action === 'HOLD' ? 'Market rising while AI is HOLD.' : marketBias === 'FALLING' && action === 'HOLD' ? 'Market falling while AI is HOLD.' : 'No notable market/AI divergence.';
  const consensus = useMemo(() => { const votes = Object.values(decision?.votes || {}).map((v) => String(v).toUpperCase()); const buy = votes.filter((v) => v === 'BUY').length; const sell = votes.filter((v) => v === 'SELL').length; const hold = votes.filter((v) => v === 'HOLD').length; const total = votes.length; if (!total) return { label: 'NO DATA', percent: 0, buy, sell, hold }; const max = Math.max(buy, sell, hold); const label = max === buy ? 'BUY' : max === sell ? 'SELL' : 'HOLD'; return { label, percent: max / total * 100, buy, sell, hold }; }, [decision]);
  const radarValues = useMemo(() => { const s = decision?.market_scores || {}; return ['sentiment','technical','decision','forecast','mimic_trader','consensus'].map((key) => Math.max(-1, Math.min(1, Number.isFinite(Number(s[key])) ? Number(s[key]) : 0))); }, [decision]);
  const radarData = useMemo(() => ({ labels: ['Sentiment','Technical','Decision','Forecast','Trader','Consensus'], datasets: [{ label: 'Score', data: radarValues, fill: true, borderWidth: 2, pointRadius: 3 }] }), [radarValues]);
  const radarOptions = useMemo(() => ({ responsive: true, maintainAspectRatio: false, scales: { r: { min: -1, max: 1, ticks: { stepSize: .5 } } }, plugins: { legend: { display: false } } }), []);
  const chart = useMemo(() => { const points = Array.isArray(market?.points) ? market.points.slice(-60) : []; const labels = points.map((p, i) => p.timestamp ? new Date(Number(p.timestamp) * 1000).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) : String(i + 1)); const prices = points.map((p) => Number(p.price)); const position = positions[0]; const entry = Number(position?.entry_price || 0); const qty = Number(position?.quantity || 0); const pnl = prices.map((p) => entry > 0 && qty > 0 ? (p - entry) * qty : null); const forecastScore = Number(decision?.market_scores?.forecast || 0); const forecast = prices.map((p, i) => p * (1 + forecastScore * .004 * (i + 1))); return { labels, datasets: [{ label: 'Market Price', data: prices, borderColor: '#666', backgroundColor: 'transparent', yAxisID: 'price', tension: .25, pointRadius: 0 }, { label: 'Position PnL', data: pnl, borderColor: '#16a34a', backgroundColor: 'transparent', yAxisID: 'pnl', tension: .2, pointRadius: 0 }, { label: 'AI Forecast', data: forecast, borderColor: '#2563eb', backgroundColor: 'transparent', yAxisID: 'price', borderDash: [6,4], tension: .25, pointRadius: 0 }] }; }, [market, decision, positions]);
  const chartOptions = useMemo(() => ({ responsive: true, maintainAspectRatio: false, interaction: { mode: 'index', intersect: false }, scales: { price: { type: 'linear', position: 'left', title: { display: true, text: 'Price (IDR)' } }, pnl: { type: 'linear', position: 'right', title: { display: true, text: 'PnL (IDR)' }, grid: { drawOnChartArea: false } } }, plugins: { legend: { display: true, position: 'bottom' } } }), []);
  return <Grid container spacing={3} sx={{ mb: 3 }}>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">System Health</Typography><Typography variant="caption" color="text.secondary">Live read-only diagnostics.</Typography><Stack spacing={1.3} sx={{ mt: 2 }}><Indicator label="Database" ok={health?.database?.connected === true} value={health?.database?.connected ? 'CONNECTED' : 'DISCONNECTED'} /><Indicator label="Market data" ok={health?.market_data?.fresh === true} value={health?.market_data?.fresh ? 'FRESH' : 'STALE'} /><Indicator label="Mode" ok={String(health?.mode || 'paper').toUpperCase() === 'PAPER'} value={String(health?.mode || 'paper').toUpperCase()} /><Indicator label="Engine" ok={health?.engine?.enabled === true} value={health?.engine?.enabled ? 'ARMED' : 'OFF'} /></Stack></Paper></Grid>
    <Grid item xs={12} md={8}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Agent Score Radar</Typography><Typography variant="caption" color="text.secondary">Positive values lean BUY; negative values lean SELL. This visualization never executes a trade.</Typography><Box sx={{ height: 270, mt: 1 }}>{decision?.market_scores ? <Radar data={radarData} options={radarOptions} /> : <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', color: 'text.secondary' }}>Waiting for an AI result...</Box>}</Box><Stack direction="row" spacing={1} flexWrap="wrap"><Chip size="small" label="+1 BUY" /><Chip size="small" label="0 neutral" /><Chip size="small" label="−1 SELL" /></Stack></Paper></Grid>
    <Grid item xs={12}><Paper sx={{ p: 2.5 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'flex-start', md: 'center' }}><Box><Typography variant="h6">Trading Flow Chart</Typography><Typography variant="caption" color="text.secondary">Market price, current-position PnL and AI forecast.</Typography></Box><Chip label={action} color={action === 'BUY' ? 'success' : action === 'SELL' ? 'error' : 'default'} /></Stack><Box sx={{ height: 360, mt: 2 }}>{chart.labels.length > 1 ? <Line data={chart} options={chartOptions} /> : <Box sx={{ height: '100%', display: 'grid', placeItems: 'center', color: 'text.secondary' }}>Collecting live market points…</Box>}</Box></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Position Control</Typography><Typography variant="caption" color="text.secondary">Server-authoritative limit. Hard maximum: 3.</Typography><FormControl fullWidth size="small" sx={{ mt: 2 }}><InputLabel>Maximum positions</InputLabel><Select value={maxPositions} label="Maximum positions" onChange={saveLimit}><MenuItem value={1}>1 position</MenuItem><MenuItem value={2}>2 positions</MenuItem><MenuItem value={3}>3 positions</MenuItem></Select></FormControl><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>Open: {positions.length} / {maxPositions}. Allocation per BUY: {Number(health?.position_allocation || .1) * 100}%.</Typography></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Market vs AI</Typography><Typography variant="caption" color="text.secondary">Observation only.</Typography><Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 2, mb: 1 }}>{Number.isFinite(move) && move !== 0 ? (move > 0 ? <TrendingUp color="success" /> : <TrendingDown color="error" />) : <Remove color="disabled" />}<Typography variant="h5">{Number.isFinite(move) ? `${move > 0 ? '+' : ''}${move.toFixed(2)}%` : '—'}</Typography></Stack><Typography variant="body2">{observation}</Typography><Typography variant="caption" color="text.secondary">AI confidence: {Number.isFinite(confidencePct) ? `${confidencePct.toFixed(1)}%` : '—'}</Typography></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">AI Consensus</Typography><Typography variant="caption" color="text.secondary">Current agent agreement.</Typography><Chip sx={{ mt: 2, mb: 1 }} label={`${consensus.label}${consensus.percent ? ` ${consensus.percent.toFixed(0)}%` : ''}`} color={consensus.label === 'BUY' ? 'success' : consensus.label === 'SELL' ? 'error' : 'default'} /><Typography variant="body2">BUY {consensus.buy} · HOLD {consensus.hold} · SELL {consensus.sell}</Typography><Typography variant="caption" color="text.secondary">Market condition: {marketBias} · {condition}</Typography></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Paper Session</Typography><Typography variant="caption" color="text.secondary">Runtime and decision activity.</Typography><Grid container spacing={1.5} sx={{ mt: 1 }}><Grid item xs={6}><Typography variant="caption" color="text.secondary">Runtime</Typography><Typography>{Number(runtimeHours).toFixed(1)} h</Typography></Grid><Grid item xs={6}><Typography variant="caption" color="text.secondary">Cycles</Typography><Typography>{cycles}</Typography></Grid><Grid item xs={4}><Typography variant="caption" color="text.secondary">BUY</Typography><Typography color="success.main">{counts?.BUY || 0}</Typography></Grid><Grid item xs={4}><Typography variant="caption" color="text.secondary">SELL</Typography><Typography color="error.main">{counts?.SELL || 0}</Typography></Grid><Grid item xs={4}><Typography variant="caption" color="text.secondary">HOLD</Typography><Typography>{counts?.HOLD || 0}</Typography></Grid></Grid></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Decision History</Typography><Typography variant="caption" color="text.secondary">Recent decisions captured by the dashboard.</Typography><Stack spacing={.8} sx={{ mt: 1.5 }}>{decisionHistory.slice(0, 6).map((item, i) => <Card key={`${item.timestamp}-${i}`} variant="outlined"><CardContent sx={{ py: .8, '&:last-child': { pb: .8 } }}><Stack direction="row" justifyContent="space-between"><Typography variant="caption">{new Date(item.timestamp).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}</Typography><Chip size="small" label={item.action} color={item.action === 'BUY' ? 'success' : item.action === 'SELL' ? 'error' : 'default'} /></Stack><Typography variant="caption" color="text.secondary">{item.pair} · market {item.move == null ? '—' : `${item.move > 0 ? '+' : ''}${Number(item.move).toFixed(2)}%`} · confidence {Number(item.confidence || 0).toFixed(0)}%</Typography></CardContent></Card>)}{decisionHistory.length === 0 && <Typography color="text.secondary">No observations yet.</Typography>}</Stack></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Risk Snapshot</Typography><Typography variant="caption" color="text.secondary">Paper account guardrails.</Typography><Stack spacing={1.2} sx={{ mt: 2 }}><Stack direction="row" justifyContent="space-between"><Typography>Open positions</Typography><Typography>{positions.length}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>Max positions</Typography><Typography>{maxPositions}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography>Allocation / trade</Typography><Typography>{Number(health?.position_allocation || .1) * 100}%</Typography></Stack><Chip label={positions.length <= maxPositions ? 'WITHIN LIMIT' : 'REVIEW'} color={positions.length <= maxPositions ? 'success' : 'warning'} /></Stack></Paper></Grid>
    <Grid item xs={12} md={4}><Paper sx={{ p: 2.5, height: '100%' }}><Typography variant="h6">Target Review</Typography><Typography variant="caption" color="text.secondary">Benchmark only.</Typography>{['daily','weekly','monthly'].map((period) => <Box key={period} sx={{ mt: 1.2 }}><Stack direction="row" justifyContent="space-between"><Typography variant="caption">{period.toUpperCase()}</Typography><Typography variant="caption">{Number(targets?.[period]) > 0 ? idr(targets[period]) : 'not set'}</Typography></Stack><LinearProgress variant="determinate" value={Number(targets?.[period]) > 0 ? Math.min(100, Math.max(0, Number(dailyActual) / Number(targets[period]) * 100)) : 0} /></Box>)}</Paper></Grid>
    <Grid item xs={12}><Paper sx={{ p: 2.5 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'flex-start', md: 'center' }}><Box><Typography variant="h6">Paper History Library</Typography><Typography variant="caption" color="text.secondary">Persistent snapshots from Supabase when available; Durable Object fallback otherwise.</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><TextField size="small" type="date" label="Trading date" value={historyDate} onChange={(e) => setHistoryDate(e.target.value)} InputLabelProps={{ shrink: true }} /><Chip label={`${history.length} cycles`} /></Stack></Stack>{historyError && <Typography color="warning.main" sx={{ mt: 1 }}>{historyError}</Typography>}{historyLoading ? <LinearProgress sx={{ mt: 2 }} /> : history.length === 0 ? <Typography color="text.secondary" sx={{ mt: 2 }}>No persistent cycles for {historyDate}.</Typography> : <Stack spacing={1} sx={{ mt: 2 }}>{history.map((row) => <Card key={row.id || row.cycle_at} variant="outlined"><CardContent sx={{ py: 1.2 }}><Grid container spacing={1}><Grid item xs={12} md={2}><Typography variant="subtitle2">{row.cycle_at ? new Date(row.cycle_at).toLocaleTimeString('id-ID') : '—'}</Typography><Typography variant="caption" color="text.secondary">{row.pair}</Typography></Grid><Grid item xs={6} md={1}><Chip size="small" label={row.action} color={row.action === 'BUY' ? 'success' : row.action === 'SELL' ? 'error' : 'default'} /></Grid><Grid item xs={6} md={2}><Typography variant="caption" color="text.secondary">Price</Typography><Typography>{idr(row.price)}</Typography></Grid><Grid item xs={6} md={2}><Typography variant="caption" color="text.secondary">Equity</Typography><Typography>{idr(row.portfolio_value)}</Typography></Grid><Grid item xs={6} md={1}><Typography variant="caption" color="text.secondary">Confidence</Typography><Typography>{Number(row.confidence || 0).toFixed(0)}%</Typography></Grid><Grid item xs={6} md={2}><Typography variant="caption" color="text.secondary">PnL</Typography><Typography color={Number(row.daily_pnl || 0) >= 0 ? 'success.main' : 'error.main'}>{idr(row.daily_pnl)}</Typography></Grid></Grid><Typography variant="caption" color="text.secondary">Positions {row.active_positions ?? 0} · Consensus {row.consensus_action || '—'} · Source {row.engine_source || '—'}</Typography></CardContent></Card>)}</Stack>}</Paper></Grid>
  </Grid>;
}
