import React,{useEffect,useState} from 'react';
import {Alert,Box,Button,Chip,FormControl,InputLabel,MenuItem,Paper,Select,Stack,Typography} from '@mui/material';
import axios from 'axios';
const pct=v=>`${Number(v||0).toFixed(2)}%`;
const CATALOG=[
 {name:'CONSERVATIVE',label:'Conservative',description:'Wider protection and earlier profit activation. Lower variance; accepts smaller reward targets.',settings:{stop_atr_multiplier:1.8,risk_reward_ratio:1.4,profit_activation_pct:.6,break_even_trigger_r:.8,trailing_atr_multiplier:1.5,hard_take_profit_enabled:true,max_hold_minutes:12}},
 {name:'BALANCED',label:'Balanced',description:'Baseline policy for paper validation. Middle ground between protection and reward.',settings:{stop_atr_multiplier:1.5,risk_reward_ratio:2,profit_activation_pct:1,break_even_trigger_r:1,trailing_atr_multiplier:1.25,hard_take_profit_enabled:false,max_hold_minutes:15}},
 {name:'AGGRESSIVE',label:'Aggressive',description:'Tighter initial protection and larger reward target. Higher variance and lower tolerance for noise.',settings:{stop_atr_multiplier:1.1,risk_reward_ratio:2.2,profit_activation_pct:.5,break_even_trigger_r:1,trailing_atr_multiplier:1,hard_take_profit_enabled:false,max_hold_minutes:10}}
];
export default function RiskTemplateControl(){
 const[settings,setSettings]=useState(null),[selected,setSelected]=useState('BALANCED'),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{setError('');const r=await axios.get('/api/dashboard/paper/risk',{params:{_ts:Date.now()}});const d=r.data||{};setSettings(d.risk_settings||{});setSelected(String(d.risk_settings?.tp_sl_template||'BALANCED'))}catch(e){setError(e.response?.data?.detail||'TP/SL policy unavailable')}};
 useEffect(()=>{load()},[]);
 const active=CATALOG.find(x=>x.name===selected)||CATALOG[1];
 const choose=async e=>{const name=e.target.value;const template=CATALOG.find(x=>x.name===name)||CATALOG[1];setSelected(name);setSaving(true);setError('');try{const risk_settings={tp_sl_template:name,stop_loss_mode:'ATR',take_profit_mode:'RISK_REWARD',...template.settings};const r=await axios.post('/api/dashboard/paper/settings',{risk_settings});setSettings(r.data?.risk_settings||r.data?.state?.risk_settings||risk_settings)}catch(err){setError(err.response?.data?.detail||'Failed to apply TP/SL template');await load()}finally{setSaving(false)}};
 return <Paper sx={{p:2.5,height:'100%'}}><Typography variant="h6">TP / SL Policy</Typography><Typography variant="caption" color="text.secondary">Human-controlled policy. Stored server-side and enforced by the deterministic risk engine.</Typography><FormControl fullWidth size="small" sx={{mt:2}} disabled={saving}><InputLabel>TP / SL aggressiveness</InputLabel><Select value={selected} label="TP / SL aggressiveness" onChange={choose}>{CATALOG.map(x=><MenuItem key={x.name} value={x.name}>{x.label}</MenuItem>)}</Select></FormControl><Box sx={{mt:1.5}}><Stack direction="row" spacing={1} sx={{mb:1,flexWrap:'wrap'}}><Chip size="small" label={active.label}/><Chip size="small" label={`SL ${active.settings.stop_atr_multiplier} ATR`}/><Chip size="small" label={`RR ${active.settings.risk_reward_ratio}R`}/><Chip size="small" label={`${active.settings.max_hold_minutes} min max`}/></Stack><Typography variant="body2" color="text.secondary">{active.description}</Typography><Typography variant="caption" color="text.secondary" sx={{display:'block',mt:1}}>Activation {pct(active.settings.profit_activation_pct)} · BE {active.settings.break_even_trigger_r}R · Trail {active.settings.trailing_atr_multiplier} ATR · Hard TP {active.settings.hard_take_profit_enabled?'ON':'OFF'}</Typography></Box>{settings&&<Typography variant="caption" sx={{display:'block',mt:1}}>Server policy: <strong>{settings.tp_sl_template||'BALANCED'}</strong></Typography>}{error&&<Alert severity="warning" sx={{mt:1.5}}>{error}</Alert>}<Button size="small" variant="outlined" onClick={load} disabled={saving} sx={{mt:1.5}}>Refresh policy</Button></Paper>;
}
