create table if not exists public.paper_history (
  id bigint generated by default as identity primary key,
  cycle_at timestamptz not null default now(),
  trading_date date not null default current_date,
  pair text not null,
  action text not null check (action in ('BUY','SELL','HOLD')),
  raw_action text,
  confidence numeric not null default 0 check (confidence >= 0 and confidence <= 100),
  price numeric not null default 0,
  balance numeric not null default 0,
  portfolio_value numeric not null default 0,
  daily_pnl numeric not null default 0,
  total_pnl numeric not null default 0,
  active_positions integer not null default 0,
  positions jsonb not null default '[]'::jsonb,
  agent_votes jsonb not null default '{}'::jsonb,
  market_scores jsonb not null default '{}'::jsonb,
  confidence_components jsonb not null default '{}'::jsonb,
  consensus_action text,
  consensus_score numeric,
  position_size numeric,
  stop_loss numeric,
  take_profit numeric,
  reasoning text,
  engine_source text,
  engine_warning text,
  created_at timestamptz not null default now()
);
create index if not exists paper_history_trading_date_idx on public.paper_history (trading_date desc, cycle_at desc);
create index if not exists paper_history_pair_cycle_idx on public.paper_history (pair, cycle_at desc);
alter table public.paper_history enable row level security;
