-- V0.2 audit integrity repair.
-- 1) Keep cycle_number monotonic within a session even if Durable Object counters reset.
-- 2) Keep decision/history trade_id synchronized with the canonical trades ledger.
-- 3) Persist an integrity event whenever a duplicate cycle number is repaired.

CREATE TABLE IF NOT EXISTS public.paper_integrity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  severity text NOT NULL DEFAULT 'ERROR',
  event_type text NOT NULL,
  cycle_id text,
  session_id text,
  decision_id bigint,
  trade_id bigint,
  symbol text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.paper_integrity_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_paper_integrity_events_created
  ON public.paper_integrity_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_paper_integrity_events_cycle
  ON public.paper_integrity_events(cycle_id);

CREATE OR REPLACE FUNCTION public.normalize_paper_cycle_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  existing_max bigint;
  linked_cycle bigint;
  requested_cycle bigint;
BEGIN
  -- paper_history must inherit the already-normalized number from its decision.
  IF NEW.cycle_id IS NOT NULL AND TG_TABLE_NAME = 'paper_history' THEN
    SELECT d.cycle_number
      INTO linked_cycle
      FROM public.decisions d
     WHERE d.cycle_id = NEW.cycle_id
     ORDER BY d.id DESC
     LIMIT 1;

    IF linked_cycle IS NOT NULL THEN
      NEW.cycle_number := linked_cycle;
      RETURN NEW;
    END IF;
  END IF;

  IF NEW.session_id IS NOT NULL AND NEW.cycle_number IS NOT NULL THEN
    requested_cycle := NEW.cycle_number;

    SELECT max(cycle_number)
      INTO existing_max
      FROM public.decisions d
     WHERE d.session_id = NEW.session_id
       AND d.cycle_number IS NOT NULL;

    SELECT greatest(existing_max, max(ph.cycle_number))
      INTO existing_max
      FROM public.paper_history ph
     WHERE ph.session_id = NEW.session_id
       AND ph.cycle_number IS NOT NULL;

    IF existing_max IS NOT NULL AND requested_cycle <= existing_max THEN
      NEW.cycle_number := existing_max + 1;

      INSERT INTO public.paper_integrity_events(
        severity, event_type, cycle_id, session_id, symbol, details
      )
      VALUES (
        'WARN',
        'DUPLICATE_CYCLE_NUMBER_REPAIRED',
        NEW.cycle_id,
        NEW.session_id,
        COALESCE(NEW.symbol, NEW.pair),
        jsonb_build_object(
          'requested', requested_cycle,
          'assigned', NEW.cycle_number,
          'previous_max', existing_max
        )
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_decisions_normalize_cycle_number ON public.decisions;
CREATE TRIGGER trg_decisions_normalize_cycle_number
BEFORE INSERT ON public.decisions
FOR EACH ROW
EXECUTE FUNCTION public.normalize_paper_cycle_number();

DROP TRIGGER IF EXISTS trg_paper_history_normalize_cycle_number ON public.paper_history;
CREATE TRIGGER trg_paper_history_normalize_cycle_number
BEFORE INSERT ON public.paper_history
FOR EACH ROW
EXECUTE FUNCTION public.normalize_paper_cycle_number();

CREATE OR REPLACE FUNCTION public.reconcile_paper_trade_links()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.decision_id IS NOT NULL THEN
    UPDATE public.decisions
       SET trade_id = NEW.id
     WHERE id = NEW.decision_id
       AND trade_id IS DISTINCT FROM NEW.id;

    UPDATE public.paper_history
       SET trade_id = NEW.id
     WHERE decision_id = NEW.decision_id
       AND trade_id IS DISTINCT FROM NEW.id;
  END IF;

  IF NEW.exit_decision_id IS NOT NULL THEN
    UPDATE public.decisions
       SET trade_id = NEW.id
     WHERE id = NEW.exit_decision_id
       AND trade_id IS DISTINCT FROM NEW.id;

    UPDATE public.paper_history
       SET trade_id = NEW.id
     WHERE decision_id = NEW.exit_decision_id
       AND trade_id IS DISTINCT FROM NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_trades_reconcile_paper_links ON public.trades;
CREATE TRIGGER trg_trades_reconcile_paper_links
AFTER INSERT OR UPDATE OF decision_id, exit_decision_id, status ON public.trades
FOR EACH ROW
EXECUTE FUNCTION public.reconcile_paper_trade_links();

-- Repair known historical links immediately.
UPDATE public.decisions d
   SET trade_id = t.id
  FROM public.trades t
 WHERE t.decision_id = d.id
   AND d.trade_id IS DISTINCT FROM t.id;

UPDATE public.decisions d
   SET trade_id = t.id
  FROM public.trades t
 WHERE t.exit_decision_id = d.id
   AND d.trade_id IS DISTINCT FROM t.id;

UPDATE public.paper_history ph
   SET trade_id = d.trade_id
  FROM public.decisions d
 WHERE ph.decision_id = d.id
   AND d.trade_id IS NOT NULL
   AND ph.trade_id IS DISTINCT FROM d.trade_id;
